### ISSUE TITLE
Upscalling

### ISSUE THREAD

**Issue by BennettFourr** [SytanSD/Sytan-SDXL-ComfyUI#10]
What model do you recommend for upscalling?

**Comment by Aunalise** [comment]
I'll put my 2 cents in since I just did testing with this workflow.
I found that 4x_NMKD-Siax_200k to be excellent. 
I also have found 4x_foolhardy_Remacri to be great, too, and what is best depends on the kind of detail, such as hair and clothing texture, versus skin or something else.

ALSO, with image upscaling, you MUST use a VAE loader and load the SDXL fixed VAE. don't use anything that is baked in that derives from the SDXL Base. It is broken, and when doing an image upscale, you can see those errors blown up and causing significant issues in a subsequent KSampler. An 8x image upscale will really expose this issue.
