### ISSUE TITLE
Issue: server process killed without error message.

### ISSUE THREAD

**Issue by cosmic-zip** [SytanSD/Sytan-SDXL-ComfyUI#14]
**Issue**: server process killed without error message.
**details**: 

- I'm using default values 
- Only 3Gb of vram used
- My 16gb are fine
- No details, de Default ComfyUI works without problem

**config**: Comfy UI plus + / Sytan-SDXL-ComfyUI 
**article** that i'm use to start with Sytan SDXL:  https://aituts.com/comfyui/

**PC Config:**

- OS: Ubuntu 22.04.3 LTS x86_64 
- Kernel: 6.2.0-32-generic 
- Shell: bash 5.1.16 
- Resolution: 2560x1080 
- DE: GNOME 42.9 
- CPU: Intel i5-10400 (12) @ 4.300GHz 
- GPU: NVIDIA 3050
- Memory: 4490MiB / 15831MiB

![error](https://github.com/SytanSD/Sytan-SDXL-ComfyUI/assets/36008397/1f1f3c72-8b1f-42ca-8a2e-695e258d9534)

Especial thanks, for review

**Comment by SytanSD** [comment]
Sorry for the late response. This seems like more of an issue with ComfyUI as a whole rather than the workflow I provided. I hope you have been able to solve this issue in the time passed.

I have seen similar errors encountered from other workflows with different hardware. I am not too sure what causes it, nor do I know how to solve it unfortunately

**Comment by cosmic-zip** [comment]
That's okay, I don't remember this problem anymore. I'm just using the new models with the default ConfyUI and I believe that in a few years AI-generated images will definitely have the same quality as SDXL by default. Appreciate you for your response.
