### ISSUE TITLE
Your config 0.5 giving simple prompts terrible results 

### ISSUE THREAD

**Issue by mirek190** [SytanSD/Sytan-SDXL-ComfyUI#3]
For instance simple prompt "Elvis Presley " - no any extra negative , positive prompts  

Giving in 99% really bad results ... just really bad 

BUT this config for simple question like "Elvis Presley " - no any extra negative , positive prompts  
[workflow_SD_XL_0.9_v2.zip](https://github.com/SytanSD/Sytan-SDXL-ComfyUI/files/12006193/workflow_SD_XL_0.9_v2.zip)

Works almost perfectly in 99% of time and giving proper results for simple questions.

I hope this config will help you to make your better.

**Comment by SytanSD** [comment]
Hello there, sorry for the late response, I have been dealing with some issues associated with my new PC.

I took a look over your workflow, and I note that the workflow itself is not what lends it to working better with very basic/limited prompts, but rather your use of the normal text encoders instead of the ones specifically made for the SDXL base and refiner

While using these two refiners will help get better results when used on a low level, the specialized refiners can help get significantly better/higher detail results when putting in a little more time into the prompts.

Attached below is a comparison of a weak prompt using the normal text encoders on your workflow, and a strong prompt using the specialized text encoders on mine

I was looking for a realistic photograph of a tiger in a field of colorful wildflowers with mountains off in the distance, and a cloudy sky at sunset

First is yours, second is mine. There is no better option here, just tools made for different results

![image](https://github.com/SytanSD/Sytan-SDXL-ComfyUI/assets/122675732/f200507e-5e97-44f6-8a73-c36bed0a0204)

![image](https://github.com/SytanSD/Sytan-SDXL-ComfyUI/assets/122675732/6c2dd389-6125-450d-8179-89d807fbfd58)

**Comment by mirek190** [comment]
You're right .. your looks more realistic but is also works with hands well?
Prompt “Diagrams Of How To Draw Hands”.

I tested on www here

**Comment by mirek190** [comment]
had to update comment .... sorry ;)
